apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgresql
    type: postgres
    access: proxy
    url: host.docker.internal:5432
    database: trade_logs
    user: bot
    secureJsonData:
      password: "NUOCh2o#mC2#"
    jsonData:
      sslmode: disable
      postgresVersion: 1400
      timescaledb: false
    editable: false
